#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

echo "run crontab -e while logged in as autograder"

# autograde every 15 minutes
# try to run a command, but fail immediately if it's already running
echo "*/15 * * * * flock -n /var/lock/autograder.lock autograde"

# update scripts every hour
echo "0 * * * * refresh-class-utils"