#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

# make sure we're in the directory containing the other scripts
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
cd $DIR

# update the system
apt update
apt upgrade

# install required packages

PACKAGES="build-essential make gcc g++ gdb clang clang-format vim emacs python3 python3-pip python3-pygame python3-tk idle3 git default-jdk quota zip unzip valgrind sshpass"

apt install $PACKAGES
apt clean
apt autoclean
apt autopurge
apt autoremove

# pip3 install Pillow pygame

mv include/* /usr/local/include

echo "Setting the hostname"
hostnamectl set-hostname cscivm

echo "Make sure this folder is in /class-utils"

echo "Remember to clone the starter code into /starter-code"

echo "run refresh-class-utils"

echo "Remember to add .vimrc, etc."