#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

# make sure we're in the directory containing the other scripts
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
cd $DIR

# first add files to the /etc/skel directory. .vimrc, Edit default umask
echo "Before doing this, make sure you've added/edited the necessary files to the /etc/skel directory. E.g., .vimrc, edit the umask to 077 in .bashrc. Press Enter to continue."
read -n 1

# add {teacher, bot, student} groups
getent group teacher || groupadd teacher
getent group bot || groupadd bot
getent group student || groupadd student

getent group docker || groupadd docker

# add users {lawt, autograder, test_08675309}
useradd -m -N -g teacher -G sudo -s /bin/bash -c "Lawton Nichols" -K UID_MIN=1000 -K UID_MAX=1999 -K UMASK=077 lawt
useradd -m -N -g bot -G sudo,docker -s /bin/bash -c "Autograder" -K UID_MIN=1000 -K UID_MAX=1999 -K UMASK=077 autograder
useradd -m -N -g student -s /bin/bash -c "Test Student" -K UID_MIN=2000 -K UMASK=077 test_08675309

# echo -e "linuxpassword\nlinuxpassword" | passwd linuxuser
echo "Enter password for lawt"
passwd lawt
echo "Enter password for autograder"
passwd autograder
echo "Enter password for test_08675309"
passwd test_08675309

# update the system
apt update
apt upgrade

# install required packages

PACKAGES="build-essential make gcc g++ gdb clang clang-format vim python3 git default-jdk docker.io quota zip unzip valgrind sshpass ripgrep"

apt install $PACKAGES
apt clean
apt autoclean
apt autopurge
apt autoremove

systemctl enable docker

cp include/* /usr/local/include

# configure quotas
# https://www.tecmint.com/set-filesystem-disk-quotas-on-ubuntu/
# https://www.digitalocean.com/community/tutorials/how-to-enable-user-and-group-quotas
  # if your system support -p option of edquota then I think it is what you need.
  # Create prototype user, set up quota, then just run
  # edquota -p prototypeuser targetuser
echo -e "We're about to edit /etc/fstab for quotas---you need to add \",usrquota\". Press Enter to continue."
read -n 1
nano /etc/fstab
mount -o remount /
quotacheck -cum /
quotaon /

echo "Setting the quota for test_08675309."
setquota -u test_08675309 100M 110M 0 0 /
quota -vs test_08675309

ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

echo "Setting the hostname"
hostnamectl set-hostname lawtonsclass

mkdir -p ~autograder/bin ~autograder/submissions-graded ~autograder/submissions-to-grade ~autograder/grades
touch ~autograder/available-assignments
chown -R autograder:bot ~autograder
mkdir -p ~lawt/bin
chown -R lawt:teacher ~lawt/bin

echo "Now you should run refresh-class-utils.sh, set up docker, and set up cron"
echo "Also set up the autograder account--clone the autograders repo, add the available-assignments file"
echo "Move this folder to lawt's ~ if you put it somewhere else."

echo "You might want to alias g=git to make your life easier."
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.st status
git config --global alias.c commit

echo "Add your public key to authorized_keys"

echo "Add default umask to profile.d"
