#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

# make sure we're in the directory containing the other scripts
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
cd $DIR

# update the system
apt update
apt upgrade

# install required packages

PACKAGES="build-essential make cmake gcc g++ gdb clang clangd clang-format vim neovim emacs python3 python3-pip git default-jdk quota zip unzip valgrind sshpass nodejs curl zsh"

apt-get purge libreoffice* gimp*
apt install $PACKAGES
apt clean
apt autoclean
apt autopurge
apt autoremove

# pip3 install Pillow pygame

mv include/* /usr/local/include

echo "Adding vimrc"
cp skel/vimrc ~/.vimrc

echo "Installing VS Code"
snap install --classic code 

echo "Installing Racket repository"
add-apt-repository ppa:plt/racket
apt update
# should students install racket themselves?
#apt install racket

echo "Make sure this folder is in /class-utils"

echo "Remember to clone the starter code via https into /starter-code"

echo "Remember to run ./refresh-class-utils to install all the scripts"

echo "Remember to install VS Code plugins! (C++, Prettier, and Bracket Pair Colorizer )"

echo "Remember to install racket if you're teaching CSCI 26"

echo "Install oh my zsh using:"
echo 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

echo "Remember to turn off the screensaver and disable the lock screen"

echo "ssh to the server once; otherwise turnin doesn't trust it and won't work"

echo "Remember to shrink the filesystem before you zip it"