#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script as root"
    exit 1
fi

# usage: add-student username
# todo: add full name

useradd -m -N -g student -s /bin/bash -c "$1" -K UID_MIN=2000 -K UMASK=077 $1

# TODO: use chpasswd instead
echo -e "$1\n$1" | passwd $1

# expire the password
passwd --expire $1

setquota -u $1 100M 110M 0 0 /
