#!/bin/bash

if [ "$(whoami)" != "autograder" ]; then
  echo "Script must be run as user: autograder"
  exit 1
fi

# for each student submission, run autograde-one-submission
for submission in ~/submissions-to-grade/*.zip; do
  autograde-one-submission $submission
  mv $submission ~/submissions-graded
done