#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

cd /class-utils
git checkout -- .
git clean -f
git pull
cp /class-utils/virtual-machine-bin/* /usr/local/bin/
chmod 755 /usr/local/bin/*