#!/bin/bash

read -p "Enter your server username: " username
rsync -rtv "$username"@server.lawtonsclass.com:~/.autograder ~
echo ""
echo "Assuming you didn't see any error messages, your grades have been downloaded!"
echo "Please yell at Lawton if something went wrong."
echo "Run view-grades to see if anything changed."