#!/bin/bash

function get-assignment-class {
local result=$(python3 - <<END
print("$1".split('@')[0])
END
)
  echo $result
}

function get-assignment-assignment {
local result=$(python3 - <<END
print("$1".split('@')[1])
END
)
  echo $result
}

# class-assignment-username.zip

user=$(whoami)
class=$(get-assignment-class "$1")
assignment=$(get-assignment-assignment "$1")

files="${@:2}"

# turn in the assignment

rm -rf ~/.autogradertmp
mkdir ~/.autogradertmp
cp $files ~/.autogradertmp
cd ~/.autogradertmp
zip $user-$class-$assignment.zip *
finish-turnin $user-$class-$assignment.zip $class $assignment