#!/bin/bash

function get-assignment-assignment {
local result=$(python3 - <<END
print("$1".split('@')[0])
END
)
  echo $result
}

function get-assignment-class {
local result=$(python3 - <<END
print("$1".split('@')[1])
END
)
  echo $result
}

if [ $# -lt 2 ]; then
  echo "Usage: $0 assignment@class file1 file2 ..."
  exit 1
fi

for f in "${@:2}"; do
  if [ ! -f $f ]; then
    echo "Error: $f is not a file."
    exit 1
  fi
done

# class-assignment-username.zip

user=$(whoami)
class=$(get-assignment-class "$1")
assignment=$(get-assignment-assignment "$1")

files="${@:2}"

# turn in the assignment

rm -rf ~/.autogradertmp
mkdir ~/.autogradertmp
cp $files ~/.autogradertmp
cd ~/.autogradertmp
zip $class-$assignment-$user.zip *
finish-turnin $class-$assignment-$user.zip $class $assignment $user
